import { IVoice } from '../models/Voice.js';
import {
  ELEVEN_LABS_MALE_VOICE_ID,
  ELEVEN_LABS_FEMALE_VOICE_ID,
  ELEVEN_LABS_FEMALE_SINGAPOREAN_VOICE_ID,
  ELEVEN_LABS_MALE_AMERICAN_INDIAN_VOICE_ID,
  ELEVEN_LABS_MALE_INDIAN_VOICE_ID,
  ELEVEN_LABS_INDONESIAN_YOUNG_FEMALE_VOICE_ID,
  ELEVEN_LABS_INDONESIAN_OLDER_FEMALE_VOICE_ID,
  ELEVEN_LABS_INDONESIAN_YOUNG_MALE_VOICE_ID,
  ELEVEN_LABS_INDONESIAN_OLDER_MALE_VOICE_ID,
  ELEVEN_LABS_MALAYSIAN_YOUNG_FEMALE_VOICE_ID,
  ELEVEN_LABS_MALAYSIAN_OLDER_FEMALE_VOICE_ID,
  ELEVEN_LABS_MALAYSIAN_YOUNG_MALE_VOICE_ID,
  ELEVEN_LABS_MALAYSIAN_OLDER_MALE_VOICE_ID,
  ELEVEN_LABS_TAGALOG_YOUNG_FEMALE_VOICE_ID,
  ELEVEN_LABS_TAGALOG_OLDER_FEMALE_VOICE_ID,
  ELEVEN_LABS_TAGALOG_YOUNG_MALE_VOICE_ID,
  ELEVEN_LABS_TAGALOG_OLDER_MALE_VOICE_ID,
  ELEVEN_LABS_VIETNAMESE_YOUNG_FEMALE_VOICE_ID,
  ELEVEN_LABS_VIETNAMESE_OLDER_FEMALE_VOICE_ID,
  ELEVEN_LABS_VIETNAMESE_YOUNG_MALE_VOICE_ID,
  ELEVEN_LABS_VIETNAMESE_OLDER_MALE_VOICE_ID,
  CHIRP_THAI_YOUNG_FEMALE_VOICE_ID,
  CHIRP_THAI_OLDER_FEMALE_VOICE_ID,
  CHIRP_THAI_YOUNG_MALE_VOICE_ID,
  CHIRP_THAI_OLDER_MALE_VOICE_ID,
  CHIRP_THAI_YOUNG_MALE_VOICE_ID_2,
  CHIRP_THAI_OLDER_MALE_VOICE_ID_2,
  ELEVENLABS_THAI_YOUNG_MALE_VOICE_ID,
  ELEVENLABS_THAI_OLDER_MALE_VOICE_ID,
  ELEVENLABS_THAI_YOUNG_FEMALE_VOICE_ID,
  ELEVENLABS_THAI_OLDER_FEMALE_VOICE_ID,
} from '../utils/constants.js';

/**
 * All available voice configurations for ElevenLabs TTS
 */
export const ALL_VOICES: Omit<IVoice, '_id' | 'createdAt' | 'updatedAt'>[] = [
  // English Voices
  {
    friendlyId: 'elevenlabs-male-english',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_MALE_VOICE_ID,
    name: 'English Male',
    language: 'en',
    accent: 'american',
    gender: 'male',
    ageGroup: 'middle',
    region: 'US',
    description: 'Standard American English male voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-female-english',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_FEMALE_VOICE_ID,
    name: 'English Female',
    language: 'en',
    accent: 'american',
    gender: 'female',
    ageGroup: 'middle',
    region: 'US',
    description: 'Standard American English female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-female-singaporean',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_FEMALE_SINGAPOREAN_VOICE_ID,
    name: 'Singaporean Female',
    language: 'en',
    accent: 'singaporean',
    gender: 'female',
    ageGroup: 'middle',
    region: 'Singapore',
    description: 'Singaporean English female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-male-american-indian',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_MALE_AMERICAN_INDIAN_VOICE_ID,
    name: 'American Indian Male',
    language: 'en',
    accent: 'indian',
    gender: 'male',
    ageGroup: 'middle',
    region: 'India',
    description: 'American English with Indian accent male voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-male-indian',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_MALE_INDIAN_VOICE_ID,
    name: 'Indian Male',
    language: 'en',
    accent: 'indian',
    gender: 'male',
    ageGroup: 'middle',
    region: 'India',
    description: 'Indian English male voice',
    isActive: true,
  },

  // Indonesian Voices
  {
    friendlyId: 'elevenlabs-indonesian-young-female',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_INDONESIAN_YOUNG_FEMALE_VOICE_ID,
    name: 'Indonesian Young Female',
    language: 'id',
    gender: 'female',
    ageGroup: 'young',
    region: 'Indonesia',
    description: 'Young Indonesian female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-indonesian-older-female',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_INDONESIAN_OLDER_FEMALE_VOICE_ID,
    name: 'Indonesian Older Female',
    language: 'id',
    gender: 'female',
    ageGroup: 'older',
    region: 'Indonesia',
    description: 'Older Indonesian female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-indonesian-young-male',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_INDONESIAN_YOUNG_MALE_VOICE_ID,
    name: 'Indonesian Young Male',
    language: 'id',
    gender: 'male',
    ageGroup: 'young',
    region: 'Indonesia',
    description: 'Young Indonesian male voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-indonesian-older-male',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_INDONESIAN_OLDER_MALE_VOICE_ID,
    name: 'Indonesian Older Male',
    language: 'id',
    gender: 'male',
    ageGroup: 'older',
    region: 'Indonesia',
    description: 'Older Indonesian male voice',
    isActive: true,
  },

  // Malaysian Voices
  {
    friendlyId: 'elevenlabs-malaysian-young-female',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_MALAYSIAN_YOUNG_FEMALE_VOICE_ID,
    name: 'Malaysian Young Female',
    language: 'ms',
    gender: 'female',
    ageGroup: 'young',
    region: 'Malaysia',
    description: 'Young Malaysian female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-malaysian-older-female',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_MALAYSIAN_OLDER_FEMALE_VOICE_ID,
    name: 'Malaysian Older Female',
    language: 'ms',
    gender: 'female',
    ageGroup: 'older',
    region: 'Malaysia',
    description: 'Older Malaysian female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-malaysian-young-male',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_MALAYSIAN_YOUNG_MALE_VOICE_ID,
    name: 'Malaysian Young Male',
    language: 'ms',
    gender: 'male',
    ageGroup: 'young',
    region: 'Malaysia',
    description: 'Young Malaysian male voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-malaysian-older-male',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_MALAYSIAN_OLDER_MALE_VOICE_ID,
    name: 'Malaysian Older Male',
    language: 'ms',
    gender: 'male',
    ageGroup: 'older',
    region: 'Malaysia',
    description: 'Older Malaysian male voice',
    isActive: true,
  },

  // Tagalog Voices
  {
    friendlyId: 'elevenlabs-tagalog-young-female',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_TAGALOG_YOUNG_FEMALE_VOICE_ID,
    name: 'Tagalog Young Female',
    language: 'tl',
    gender: 'female',
    ageGroup: 'young',
    region: 'Philippines',
    description: 'Young Tagalog female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-tagalog-older-female',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_TAGALOG_OLDER_FEMALE_VOICE_ID,
    name: 'Tagalog Older Female',
    language: 'tl',
    gender: 'female',
    ageGroup: 'older',
    region: 'Philippines',
    description: 'Older Tagalog female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-tagalog-young-male',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_TAGALOG_YOUNG_MALE_VOICE_ID,
    name: 'Tagalog Young Male',
    language: 'tl',
    gender: 'male',
    ageGroup: 'young',
    region: 'Philippines',
    description: 'Young Tagalog male voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-tagalog-older-male',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_TAGALOG_OLDER_MALE_VOICE_ID,
    name: 'Tagalog Older Male',
    language: 'tl',
    gender: 'male',
    ageGroup: 'older',
    region: 'Philippines',
    description: 'Older Tagalog male voice',
    isActive: true,
  },

  // Vietnamese Voices
  {
    friendlyId: 'elevenlabs-vietnamese-young-female',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_VIETNAMESE_YOUNG_FEMALE_VOICE_ID,
    name: 'Vietnamese Young Female',
    language: 'vi',
    gender: 'female',
    ageGroup: 'young',
    region: 'Vietnam',
    description: 'Young Vietnamese female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-vietnamese-older-female',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_VIETNAMESE_OLDER_FEMALE_VOICE_ID,
    name: 'Vietnamese Older Female',
    language: 'vi',
    gender: 'female',
    ageGroup: 'older',
    region: 'Vietnam',
    description: 'Older Vietnamese female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-vietnamese-young-male',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_VIETNAMESE_YOUNG_MALE_VOICE_ID,
    name: 'Vietnamese Young Male',
    language: 'vi',
    gender: 'male',
    ageGroup: 'young',
    region: 'Vietnam',
    description: 'Young Vietnamese male voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-vietnamese-older-male',
    provider: 'elevenlabs',
    providerId: ELEVEN_LABS_VIETNAMESE_OLDER_MALE_VOICE_ID,
    name: 'Vietnamese Older Male',
    language: 'vi',
    gender: 'male',
    ageGroup: 'older',
    region: 'Vietnam',
    description: 'Older Vietnamese male voice',
    isActive: true,
  },

  // Thai Voices
  {
    friendlyId: 'elevenlabs-thai-young-female',
    provider: 'elevenlabs',
    providerId: CHIRP_THAI_YOUNG_FEMALE_VOICE_ID,
    name: 'Thai Young Female (Kore)',
    language: 'th',
    gender: 'female',
    ageGroup: 'young',
    region: 'Thailand',
    description: 'Young Thai female voice - Kore',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-thai-older-female',
    provider: 'elevenlabs',
    providerId: CHIRP_THAI_OLDER_FEMALE_VOICE_ID,
    name: 'Thai Older Female (Aoede)',
    language: 'th',
    gender: 'female',
    ageGroup: 'older',
    region: 'Thailand',
    description: 'Older Thai female voice - Aoede',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-thai-young-male',
    provider: 'elevenlabs',
    providerId: CHIRP_THAI_YOUNG_MALE_VOICE_ID,
    name: 'Thai Young Male (Puck)',
    language: 'th',
    gender: 'male',
    ageGroup: 'young',
    region: 'Thailand',
    description: 'Young Thai male voice - Puck',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-thai-older-male',
    provider: 'elevenlabs',
    providerId: CHIRP_THAI_OLDER_MALE_VOICE_ID,
    name: 'Thai Older Male (Sadachbia)',
    language: 'th',
    gender: 'male',
    ageGroup: 'older',
    region: 'Thailand',
    description: 'Older Thai male voice - Sadachbia',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-thai-young-male-2',
    provider: 'elevenlabs',
    providerId: CHIRP_THAI_YOUNG_MALE_VOICE_ID_2,
    name: 'Thai Young Male 2 (Charon)',
    language: 'th',
    gender: 'male',
    ageGroup: 'young',
    region: 'Thailand',
    description: 'Young Thai male voice - Charon',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-thai-older-male-2',
    provider: 'elevenlabs',
    providerId: CHIRP_THAI_OLDER_MALE_VOICE_ID_2,
    name: 'Thai Older Male 2 (Enceladus)',
    language: 'th',
    gender: 'male',
    description: 'Older Thai male voice - Enceladus',
    isActive: true,
  },

  // Thai Voices - ElevenLabs Native
  {
    friendlyId: 'elevenlabs-th-young-male',
    provider: 'elevenlabs',
    providerId: ELEVENLABS_THAI_YOUNG_MALE_VOICE_ID,
    name: 'Thai Young Male (ElevenLabs)',
    language: 'th',
    gender: 'male',
    ageGroup: 'young',
    region: 'Thailand',
    description: 'Native ElevenLabs Thai young male voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-th-older-male',
    provider: 'elevenlabs',
    providerId: ELEVENLABS_THAI_OLDER_MALE_VOICE_ID,
    name: 'Thai Older Male (ElevenLabs)',
    language: 'th',
    gender: 'male',
    ageGroup: 'older',
    region: 'Thailand',
    description: 'Native ElevenLabs Thai older male voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-th-young-female',
    provider: 'elevenlabs',
    providerId: ELEVENLABS_THAI_YOUNG_FEMALE_VOICE_ID,
    name: 'Thai Young Female (ElevenLabs)',
    language: 'th',
    gender: 'female',
    ageGroup: 'young',
    region: 'Thailand',
    description: 'Native ElevenLabs Thai young female voice',
    isActive: true,
  },
  {
    friendlyId: 'elevenlabs-th-older-female',
    provider: 'elevenlabs',
    providerId: ELEVENLABS_THAI_OLDER_FEMALE_VOICE_ID,
    name: 'Thai Older Female (ElevenLabs)',
    language: 'th',
    gender: 'female',
    ageGroup: 'older',
    region: 'Thailand',
    description: 'Native ElevenLabs Thai older female voice',
    isActive: true,
  },
];

/**
 * Get voice by ElevenLabs voice ID
 */
export function getVoiceByProviderId(
  providerId: string,
): Omit<IVoice, '_id' | 'createdAt' | 'updatedAt'> | undefined {
  return ALL_VOICES.find((voice) => voice.providerId === providerId);
}

/**
 * Get voices by language
 */
export function getVoicesByLanguage(
  language: string,
): Omit<IVoice, '_id' | 'createdAt' | 'updatedAt'>[] {
  return ALL_VOICES.filter((voice) => voice.language === language);
}

/**
 * Get voices by gender
 */
export function getVoicesByGender(
  gender: 'male' | 'female' | 'neutral',
): Omit<IVoice, '_id' | 'createdAt' | 'updatedAt'>[] {
  return ALL_VOICES.filter((voice) => voice.gender === gender);
}
